### ISSUE TITLE
Incompatible with Python 2.6 and below

### ISSUE THREAD

**Issue by cbay** [niwinz/djorm-ext-core#1]
AttributeError: 'tuple' object has no attribute 'major'

because sys.version_info.major doesn't existe before Python 2.7.

**Comment by niwinz** [comment]
Which version you are using? I'm wondering this because I don't find any reference of version_info on djorm-ext-core

```
[3/5.0.2]{1}niwi@localhost:~/Downloads/djorm-ext-core-0.4.1> grep -R "version_info" .
[3/5.0.2]{1}niwi@localhost:~/Downloads/djorm-ext-core-0.4.1> 
```

**Comment by cbay** [comment]
My bad, it's actually in djorm_hstore and djorm_expressions! Do you want me to open an issue in those repositories?

**Comment by niwinz** [comment]
Is not necesary, I review this bug today on these repositories and fix it.
Thanks for report it.

Andrey
