### ISSUE TITLE
server_side_cursors ignores itersize argument

### ISSUE THREAD

**Issue by ghost** [niwinz/djorm-ext-core#3]
As a result, psycopg2's default value for [cursor.itersize](http://initd.org/psycopg/docs/cursor.html#cursor.itersize) is never overridden.

**Comment by niwinz** [comment]
Thanks for report it! I will fix it this afternoon.

**Comment by niwinz** [comment]
Hi! 
Sorry for my late response.

I have seen the code and itersize it not seems ignored https://github.com/niwibe/djorm-ext-core/blob/master/djorm_core/postgresql/__init__.py#L57 

Are you can give me more clues about it?

**Comment by ghost** [comment]
Hi, I am referring to the itersize argument of server_side_cursors constructor. Its value should be assigned to the `itersize` attribute on [line 22](https://github.com/niwibe/djorm-ext-core/blob/master/djorm_core/postgresql/__init__.py#L22), otherwise the attribute is always equal to `None` and consequently so is `_local_data.itersize` on line 57.

**Comment by niwinz** [comment]
You are right and... I'm totally blind!

**Comment by niwinz** [comment]
Now released a new version with this fixed.
